/*
 * This source file was generated by the Gradle 'init' task
 */
package java_chess;

import javax.swing.SwingUtilities;

import java_chess.gui.ChessGameGUI;

public class Main {
    public static void main(String[] args) throws Exception {
        SwingUtilities.invokeLater(ChessGameGUI::new);
    }
}
